### ISSUE TITLE
Text says "Managed VM's" but the product was renamed "App Engine flexible environment"

### ISSUE THREAD

**Issue by tooshel** [googlecodelabs/cloud-nodejs#2]
On this page:

https://gcplab.me/codelabs/cloud-nodejs/index.html?index=..%2F..%2Findex#11

There is mention of Managed VM's but when you click on the link there, it's about "App Engine flexible environment" which is the new correct term.

**Comment by jsimonweb** [comment]
Updated to instead mention "App Engine Flexible Environment".
