### ISSUE TITLE
Deploy step should use App Engine standard environment

### ISSUE THREAD

**Issue by steren** [googlecodelabs/cloud-nodejs#21]
The deploy step should  simply use an app.yaml with `runtime: nodejs8`.

Today, it uses `vm: true` and a `Dockerfile`: https://github.com/googlecodelabs/cloud-nodejs/tree/master/step-6-deploy
Plus the deprecated `module` attribute

`runtime: nodejs8` will deploy to App Engine standard, which will provide faster deployment time, and thus a better "getting started" experience.

CC @fhinkel

**Comment by MylesBorins** [comment]
I'll get on this tomorrow unless @fhinkel wants to take it 😊

**Comment by fhinkel** [comment]
Go for it!
