### ISSUE TITLE
Missing step for creating a datastore in the codelab, "Build a Node.js Web App Using GCP"

### ISSUE THREAD

**Issue by davidg42** [googlecodelabs/cloud-nodejs#9]
In the tutorial, there seems to be a step missing to build a datastore.  I'm new to GCP and node.js, so if I missed something obvious, please tell me.  By the way, my 

There is no dropdown for Books when I follow these steps at https://codelabs.developers.google.com/codelabs/cloud-nodejs/index.html?index=..%2F..%2Findex#6

Create Entity using the Developers Console
To test the Datastore query and see data displayed, add a Book entity from the Google Cloud Console.
1. Open a new web browser taband visit Google Cloud Console
2. Select to your Google Cloud Platform project using the dropdown at the top.
3. From the left navigation menu  under "Storage", click Datastore
4. Click Create Entity

**Comment by tswast** [comment]
There's a new step since the last time this codelab was updated. You have to enable App Engine first before you can use Cloud Datastore.

**Comment by davidg42** [comment]
Thanks, Tim. I'm afraid that doesn't tell me enough to make this codelab work. I have the App Engine enabled, and I have used Cloud Datastore for a different project. Is there more detailed information anywhere on how to make this codelab work?

**Comment by ace-n** [comment]
Hi @davidg42,

If you want a quick workaround, you should be able to skip to the *Create and delete books* section and use the web-app itself to create a `book` type in Datastore - at which point it should appear in the dropdown.

Alternatively, you can create the `book` type in Datastore by typing it in manually in the Console (where the dropdown is) and adding the following properties. (All of these properties should be **Strings**, except for `id` which should be an **Integer**.)
- id
- author
- createdBy
- description
- imageUrl
- publishedDate
- title

**Comment by davidg42** [comment]
Thanks, Ace, I learned a few things about GCP from this codelab, so I consider it mission accomplished!
